## PCA Scrapping

In [1]:
import numpy as np

In [2]:
# Data without normalization
# #-----------------------------------------------
a = [2.5, 0.5, 2.2, 1.9, 3.1, 2.3, 2, 1, 1.5, 1.1]
b = [2.4, 0.7, 2.9, 2.2, 3, 2.7, 1.6, 1.1, 1.6, 0.9]
c = [2.4, 0.9, 2.1, 2, 3, 2.7, 1.6, 1.1, 1.6, 1.9]
# #-----------------------------------------------

X = np.array([a,b])

In [3]:
'''
param data = array, 2D-array
default ddof = 1
return covariance matrix of array
'''
data = X.T
size = data.shape[0]- 1 #ddof
mean = np.mean(data, axis=0)
cov_mat = (data-mean).T.dot(data-mean) / size
cov_mat

array([[0.61655556, 0.61544444],
       [0.61544444, 0.71655556]])

In [4]:
'''Eigen Values and Eigen Vectors'''
eig_vals, eig_vecs = np.linalg.eig(cov_mat)
eig_vals, eig_vecs

(array([0.0490834 , 1.28402771]), array([[-0.73517866, -0.6778734 ],
        [ 0.6778734 , -0.73517866]]))

In [5]:
'''forming matrix and eigen values in decreasing order'''
eig_vals = eig_vals.reshape([1,len(eig_vals)])
mat = np.concatenate((eig_vals,eig_vecs), axis=0).T
mat = mat[mat[:,0].argsort()][::-1]
component = mat[:,1:]
component

array([[-0.6778734 , -0.73517866],
       [-0.73517866,  0.6778734 ]])

In [6]:
#transform the data
np.dot(data,component)

array([[-3.45911227, -0.21105048],
       [-0.85356176,  0.10692205],
       [-3.62333958,  0.34843981],
       [-2.9053525 ,  0.09448203],
       [-4.3069435 , -0.24543364],
       [-3.54409119,  0.13934727],
       [-2.53203265, -0.38575987],
       [-1.48656992,  0.01048208],
       [-2.19309595, -0.01817055],
       [-1.40732153, -0.19861046]])

In [7]:
'''Variance ratio'''
var_ratio = []
for i in eig_vals[0]:
    var_ratio.append(i/sum(eig_vals[0]))
sorted(var_ratio, reverse=True)

[0.963181314348646, 0.03681868565135408]